#!/usr/bin/env python3
# -----------------------------------------------------------------------------
# ur scene+planner bring-up (mock | isaac | real).
# Generated by the TrainIt Setup Assistant (standalone scene+planner config).
#
# Self-contained: move_group is configured by build_move_group_params() on THIS
# package's copied config + the GENERIC OMPL/Pilz/CHOMP pipelines from the
# trainit_motion_runtime framework, and the scene_manager_node injects the USD
# obstacles from config/scene.yaml. Independent of the hand-made base moveit_config.
#
#   ros2 launch yt_ur5_robotiq_trainit_config bringup.launch.py mode:=gazebo
#   ros2 launch yt_ur5_robotiq_trainit_config bringup.launch.py mode:=mock rviz:=false
# -----------------------------------------------------------------------------
import os

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import (DeclareLaunchArgument, IncludeLaunchDescription,
                            LogInfo, OpaqueFunction, RegisterEventHandler)
from launch.event_handlers import OnProcessExit
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node

from trainit_motion_runtime.trainit_moveit_config import build_move_group_params

MOVEIT_CONFIG_PACKAGE = "yt_ur5_robotiq_trainit_config"
ROBOT_NAME = "ur"
ARM_CONTROLLER = "joint_trajectory_controller"
VALID_MODES = ('mock', 'isaac', 'real', 'gazebo')
ARM_JS_REMAP_TO = None
BRIDGES = []
REAL_INCLUDE = None


def launch_setup(context, *args, **kwargs):
    mode = LaunchConfiguration("mode").perform(context)
    use_rviz = LaunchConfiguration("rviz").perform(context).lower() in ("true", "1")
    scene_config = LaunchConfiguration("scene_config").perform(context)
    if mode not in VALID_MODES:
        raise RuntimeError(f"Unknown mode '{mode}'. Valid: {', '.join(VALID_MODES)}")

    use_isaac = (mode == "isaac")
    common = {"use_sim_time": use_isaac or mode == "gazebo"}

    # Live knob for the "plans but won't execute" tuning: override the start-state
    # tolerance without rebuilding (start_tolerance:=0.0 disables the check).
    start_tol = LaunchConfiguration("start_tolerance").perform(context).strip()
    traj_exec = ({"trajectory_execution.allowed_start_tolerance": float(start_tol)}
                 if start_tol else None)

    params, mc = build_move_group_params(
        robot_name=ROBOT_NAME, moveit_config_package=MOVEIT_CONFIG_PACKAGE,
        use_isaac=use_isaac, backend=mode, trajectory_execution=traj_exec)

    share = get_package_share_directory(MOVEIT_CONFIG_PACKAGE)
    ros2_controllers_path = os.path.join(share, "config", "ros2_controllers.yaml")
    rviz_config_path = os.path.join(share, "config", "moveit.rviz")
    if not scene_config:
        scene_config = os.path.join(share, "config", "scene.yaml")

    nodes = [
        LogInfo(msg=f"[{ROBOT_NAME} scene_loader] mode={mode} planners=OMPL/Pilz/CHOMP scene={scene_config}"),
        Node(package="robot_state_publisher", executable="robot_state_publisher",
             output="screen", parameters=[mc.robot_description, common]),
        Node(package="moveit_ros_move_group", executable="move_group",
             output="screen", parameters=[params, common]),
    ]

    if mode in ("mock", "isaac"):
        rc_remap = [("/joint_states", ARM_JS_REMAP_TO)] if ARM_JS_REMAP_TO else []
        nodes.append(Node(
            package="controller_manager", executable="ros2_control_node", output="screen",
            parameters=[mc.robot_description, ros2_controllers_path, common],
            remappings=rc_remap))
        controllers = ["joint_state_broadcaster", ARM_CONTROLLER]
        spawners = [
            Node(package="controller_manager", executable="spawner",
                 arguments=[c, "--controller-manager", "/controller_manager",
                            "--controller-manager-timeout", "60"], output="screen")
            for c in controllers]
        nodes.append(spawners[0])
        for prev, nxt in zip(spawners, spawners[1:]):
            nodes.append(RegisterEventHandler(OnProcessExit(target_action=prev, on_exit=[nxt])))
    elif mode == "gazebo":
        # Gazebo Classic (ADR-0008): the gazebo_ros2_control plugin declared in the URDF
        # <gazebo> tag OWNS /controller_manager inside gzserver -> spawners ONLY, never a
        # standalone ros2_control_node. One robot_state_publisher + one move_group (above),
        # one robot_description (GazeboSystem via backend=mode), one controller_manager
        # (the plugin). A LinkAttacher grasp bridge, if any, runs via BRIDGES below.
        world = LaunchConfiguration("world").perform(context)
        # gazebo_ros2_control drives the in-gzserver controller_manager from the sim update
        # loop, so the sim must be RUNNING for controllers to activate (a paused sim makes
        # every controller switch time out). Start unpaused; GazeboSystem holds the initial
        # joint positions until the controllers take over.
        gz_args = {"gui": LaunchConfiguration("gui").perform(context),
                   "pause": "false", "verbose": "true"}
        if world:
            gz_args["world"] = world
        nodes.append(IncludeLaunchDescription(
            PythonLaunchDescriptionSource(os.path.join(
                get_package_share_directory("gazebo_ros"), "launch", "gazebo.launch.py")),
            launch_arguments=gz_args.items()))
        # Spawn at the WORLD ORIGIN (ADR-0011): the robot_description (URDF) is the single
        # source of the robot's world pose — robot_state_publisher places base_link from it in
        # RViz, and spawn_entity reproduces the SAME URDF in Gazebo, so the two agree by
        # construction. We do NOT add a spawn offset: a cell whose URDF already mounts the
        # robot (e.g. a world->base fixed joint at z=0.8) would otherwise be double-counted.
        # robot_base_world_pose is used ONLY by the importer to place the scene in base_link.
        nodes.append(Node(package="gazebo_ros", executable="spawn_entity.py", output="screen",
                          arguments=["-entity", "ur", "-topic", "robot_description"]))
        gz_controllers = ["joint_state_broadcaster", ARM_CONTROLLER]
        gz_controllers.append("gripper_position_controller")
        gz_spawners = [
            Node(package="controller_manager", executable="spawner",
                 arguments=[c, "--controller-manager", "/controller_manager",
                            "--controller-manager-timeout", "120"], output="screen")
            for c in gz_controllers]
        nodes.append(gz_spawners[0])
        for prev, nxt in zip(gz_spawners, gz_spawners[1:]):
            nodes.append(RegisterEventHandler(OnProcessExit(target_action=prev, on_exit=[nxt])))
        # Gazebo LinkAttacher grasp adapter (ADR-0010): on the grasp Bool (gripper_cmd_topic)
        # it welds the grasp target to the attach link via /ATTACHLINK|/DETACHLINK. Generated
        # by TSA from Step 7 (the base moveit_config does not carry it). Needs IFRA_LinkAttacher.
        nodes.append(Node(package=MOVEIT_CONFIG_PACKAGE, executable="link_attacher_bridge.py",
                          output="screen", parameters=[{'gripper_cmd_topic': '/gripper_cmd', 'robot_model': 'ur', 'ee_link': 'wrist_3_link', 'object_model': 'red_cube', 'object_link': 'link_1'}]))
    else:  # real: no ros2_control — the vendor bridges impersonate the same action names
        if REAL_INCLUDE:
            nodes.append(LogInfo(msg=f"[{ROBOT_NAME} scene_loader] mode=real: launching hardware bringup"))
            nodes.append(IncludeLaunchDescription(
                PythonLaunchDescriptionSource(os.path.join(
                    get_package_share_directory(REAL_INCLUDE["package"]),
                    "launch", REAL_INCLUDE["launch_file"]))))

    # Cell bridges (captured from the base bring-up): the gripper bridge, the joint-state
    # merger (so /joint_states carries the gripper joint -> complete TF), and, in real,
    # the vendor drivers. Each runs in the modes it declares.
    for b in BRIDGES:
        if mode in b.get("modes", ["mock", "isaac"]):
            node_kwargs = {"name": b["name"]} if b.get("name") else {}
            nodes.append(Node(
                package=b["package"], executable=b["executable"], output="screen",
                parameters=[dict(p) for p in b.get("parameters", [])] + [common],
                remappings=[tuple(r) for r in b.get("remappings", [])], **node_kwargs))

    # scene loader: injects the USD obstacles (config/scene.yaml) into the planning scene.
    nodes.append(Node(
        package="trainit_motion_runtime", executable="scene_manager_node",
        name="scene_manager_node", output="screen", parameters=[scene_config, common]))

    if use_rviz:
        # RViz's MotionPlanning display runs its OWN PlanningSceneMonitor. If it inherits
        # move_group's publish_planning_scene flags it starts PUBLISHING on
        # monitored_planning_scene (the very topic it also subscribes to) -> a self-sustaining
        # echo of stale FULL scenes that resurrects removed/attached objects (grasped bottles
        # reappear ~1s after grasp). Give RViz a params copy with those flags OFF so only
        # move_group publishes; RViz just subscribes.
        rviz_params = dict(params)
        for _k in ("publish_planning_scene", "publish_geometry_updates",
                   "publish_state_updates", "publish_transforms_updates"):
            rviz_params[_k] = False
        nodes.append(Node(
            package="rviz2", executable="rviz2", output="log",
            arguments=["-d", rviz_config_path], parameters=[rviz_params, common]))
    return nodes


def generate_launch_description():
    return LaunchDescription([
        DeclareLaunchArgument("mode", default_value="gazebo",
                              description="Backend: mock | isaac | real | gazebo"),
        DeclareLaunchArgument("rviz", default_value="true",
                              description="Launch RViz with the MoveIt plugin"),
        DeclareLaunchArgument("scene_config", default_value="",
                              description="scene loader params yaml (default: this package's config/scene.yaml)"),
        DeclareLaunchArgument("start_tolerance", default_value="",
                              description="override trajectory_execution.allowed_start_tolerance "
                                          "(rad); empty=framework default 0.1, 0.0=disable check"),
        DeclareLaunchArgument("world", default_value="/lab_ws/src/lrwros_ur5_workcell/worlds/pick_place_workplace.world",
                              description="Gazebo .world file (mode:=gazebo); empty=Gazebo's "
                                          "default empty world. Point it at the cell world."),
        DeclareLaunchArgument("gui", default_value="true",
                              description="Gazebo client GUI (mode:=gazebo); gui:=false = headless"),
        OpaqueFunction(function=launch_setup),
    ])
