#!/usr/bin/env python3
# -----------------------------------------------------------------------------
# ur APPLICATION bring-up — ONE command for the whole stack.
# Generated by the TrainIt Setup Assistant.
#
# Includes yt_ur5_robotiq_trainit_config/launch/bringup.launch.py (the "engine bay":
# move_group + OMPL/Pilz/CHOMP + mock/isaac/real wiring + gripper bridges + the
# scene loader + RViz), then starts the BehaviorTree application on top
# (trainit_run_bt, TrainIt Motion Runtime).
#
#   ros2 launch yt_ur5_robotiq_app bringup.launch.py mode:=gazebo
#   ros2 launch yt_ur5_robotiq_app bringup.launch.py mode:=mock bt:=false   # cell only
# -----------------------------------------------------------------------------
import os

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import (DeclareLaunchArgument, IncludeLaunchDescription,
                            LogInfo, OpaqueFunction, TimerAction)
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration

MOVEIT_CONFIG_PACKAGE = "yt_ur5_robotiq_trainit_config"
APP_PACKAGE = "yt_ur5_robotiq_app"
ROBOT_NAME = "ur"
VALID_MODES = ('mock', 'isaac', 'real', 'gazebo')


def launch_setup(context, *args, **kwargs):
    mode = LaunchConfiguration("mode").perform(context)
    rviz = LaunchConfiguration("rviz").perform(context)
    run_bt = LaunchConfiguration("bt").perform(context).lower() in ("true", "1")
    bt_delay = float(LaunchConfiguration("bt_delay").perform(context))
    if mode not in VALID_MODES:
        raise RuntimeError(f"Unknown mode '{mode}'. Valid: {', '.join(VALID_MODES)}")

    cfg_share = get_package_share_directory(MOVEIT_CONFIG_PACKAGE)
    app_share = get_package_share_directory(APP_PACKAGE)

    actions = [
        LogInfo(msg=f"[{ROBOT_NAME} app] mode={mode} cell={MOVEIT_CONFIG_PACKAGE} "
                    f"bt={'on (in %.0fs)' % bt_delay if run_bt else 'OFF (bt:=false)'}"),
        # the whole cell: move_group + planners + controllers/bridges + scene + RViz
        IncludeLaunchDescription(
            PythonLaunchDescriptionSource(
                os.path.join(cfg_share, "launch", "bringup.launch.py")),
            launch_arguments={"mode": mode, "rviz": rviz,
                              "world": LaunchConfiguration("world").perform(context)}.items()),
    ]
    if run_bt:
        # give move_group + the scene loader time to come up, then run the application
        actions.append(TimerAction(period=bt_delay, actions=[IncludeLaunchDescription(
            PythonLaunchDescriptionSource(
                os.path.join(app_share, "launch", "trainit_bt.launch.py")),
            launch_arguments={
                "planner_mode": LaunchConfiguration("planner_mode").perform(context),
                "use_sim_time": "true" if mode == "isaac" or mode == "gazebo" else "false",
                "mode": mode,
            }.items())]))
    return actions


def generate_launch_description():
    return LaunchDescription([
        DeclareLaunchArgument("mode", default_value="gazebo",
                              description="Backend: mock | isaac | real | gazebo"),
        DeclareLaunchArgument("rviz", default_value="true",
                              description="Launch RViz with the MoveIt plugin"),
        DeclareLaunchArgument("bt", default_value="true",
                              description="Run the BehaviorTree application"),
        DeclareLaunchArgument("bt_delay", default_value="15.0",
                              description="Seconds to wait for the cell before the BT starts"),
        DeclareLaunchArgument("planner_mode", default_value="ompl",
                              description="pilz | ompl | ompl_chomp"),
        DeclareLaunchArgument("world", default_value="/lab_ws/src/lrwros_ur5_workcell/worlds/pick_place_workplace.world",
                              description="Gazebo .world (mode:=gazebo); defaults to the cell "
                                          "world captured at Step 2 so Gazebo opens WITH the scene"),
        OpaqueFunction(function=launch_setup),
    ])
